#!/usr/local/bin/bash -x
if [ x$2 != xPOST-DEINSTALL ]; then
    exit
fi

export PATH="${PKG_PREFIX}/rbenv/bin:$PATH"
export RBENV_ROOT="${PKG_PREFIX}/rbenv_root"
eval "$(rbenv init -)"
rbenv rehash $1
#rm -rf $RBENV_ROOT
