# Created by: Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
# $FreeBSD$

PORTNAME=	conf_d
PORTVERSION=	0.0.4
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Python library to read configuration files, conf.d style

# disable LICENSE for now.
# bsd.licenses.mk in branch reallyenglish is old and requires confirmation from user
# ===>  py27-conf_d-0.0.4 License BSD2CLAUSE needs confirmation, but BATCH is defined.
#
# LICENSE=	BSD2CLAUSE

USE_PYTHON=	2.6+
USE_PYDISTUTILS=	yes
# disable PYDISTUTILS_AUTOPLIST, which is not implemented in bsd.python.mk in
# branch reallyenglish.
#
# PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
