# Created by: Evan Sarmiento <bsdports@wayfair.com>
# $FreeBSD$

PORTNAME=	bson
PORTVERSION=	1.10.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Full featured BSON specification implementation in Ruby

LICENSE=	APACHE20

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes
CONFLICTS=	rubygem-bson-2*

.include <bsd.port.mk>
