# Ports collection makefile for:	rubygem-mustache
# Date created:				14 May 2014
# Whom:					Mitsuru Y <mitsuruy@reallyenglish.com>
#
# $FreeBSD$

PORTNAME=	mustache
PORTVERSION=	0.99.5
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	mitsuruy@reallyenglish.com
COMMENT=	Mustache is a framework-agnostic way to render logic-free views

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/mustache

.include <bsd.port.mk>
