# $FreeBSD:$

PORTNAME=	munin-ruby
PORTVERSION=	0.2.3
CATEGORIES=	sysutils
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Create munin plugins in ruby

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
