# $FreeBSD$

PORTNAME=	Template-Plugin-YAML
PORTVERSION=	1.23
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Template plugin for YAML

LICENSE=	ART10

RUN_DEPENDS=	p5-Template-Toolkit>0:${PORTSDIR}/www/p5-Template-Toolkit \
	p5-YAML>0:${PORTSDIR}/textproc/p5-YAML

PERL_CONFIGURE=	Yes
MAN3=	Template::Plugin::YAML.3

.include <bsd.port.mk>
