# Ports collection makefile for:	rubygem-rouge
# Date created:				14 May 2014
# Whom:					Mitsuru Y <mitsuruy@reallyenglish.com>
#
# $FreeBSD$

PORTNAME=	rouge
PORTVERSION=	1.3.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	mitsuruy@reallyenglish.com
COMMENT=	A pure-ruby colorizer based on pygments

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PLIST_FILES=	bin/rougify

.include <bsd.port.mk>
