# $FreeBSD$

PORTNAME=	elasticsearch-transport
PORTVERSION=	1.0.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Ruby client for Elasticsearch

RUN_DEPENDS=	rubygem-multi_json>=0:${PORTSDIR}/devel/rubygem-multi_json \
		rubygem-faraday>=0:${PORTSDIR}/www/rubygem-faraday

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
