# Ports collection makefile for:	rubygem-patron
# Date created:				4 June 2014
# Whom:					Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
#
# $FreeBSD$

PORTNAME=	patron
PORTVERSION=	0.4.18
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Patron HTTP Client

BUILD_DEPENDS=	curl>0:${PORTSDIR}/ftp/curl

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
