# $FreeBSD$

PORTNAME=	fluent-mixin-config-placeholders
PORTVERSION=	0.2.4
CATEGORIES=	sysutils rubygems
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Configuration syntax extension mixin for fluentd plugin

LICENSE=	APACHE20

RUN_DEPENDS=	rubygem-fluentd>=0:${PORTSDIR}/sysutils/rubygem-fluentd \
		rubygem-uuidtools>=0:${PORTSDIR}/devel/rubygem-uuidtools

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
