# Ports collection makefile for:	rubygem-useragent
# Date created:				14 May 2014
# Whom:					Mitsuru Y <mitsuruy@reallyenglish.com>
#
# $FreeBSD$

PORTNAME=	useragent
PORTVERSION=	0.10.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	mitsuruy@reallyenglish.com
COMMENT=	HTTP User Agent parser

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
