# Created by: Tomoyuki Sakurai <tomoyukis@reallyenglish.com>
# $FreeBSD$

PORTNAME=	syslog-logger
PORTVERSION=	1.6.8
#PORTREVISION=	0
CATEGORIES=	sysutils
MASTER_SITES=	RG

MAINTAINER=	tomoyukis@reallyenglish.com
COMMENT=	Improved Logger replacement that logs to syslog

LICENSE=	MIT

USE_RUBY=	Yes
USE_RUBYGEMS=	Yes
RUBYGEM_AUTOPLIST=	Yes

.include <bsd.port.mk>
